### ISSUE TITLE
The problem with PythonOCC 7.5.1

### ISSUE THREAD

**Issue by GeoGroup** [chen1180/CurveEditor_pythonOCC#2]
Dear Chen:

I have just see the interesting code. When I dowmload the code and run it, there are several problem. 
(1) Name 'AIS_SD_Line' and 'AIS_SD_Point' is not defined in the AIS.py in Version 7.5.1
(2) 'AIS_InteractiveContext' object has no attribute 'HLRDeviationCoefficient'
I think this is the problem of the version. Would you please give the detail information of the code.

Many thanks
Meng

**Comment by chen1180** [comment]
Hihi Meng,

The PythonOCC version I used for this project is 7.4.0. And it still works well under the test. 
I will check the problem you have stated above in Version 7.5.1 in the future.

BRs
Baocheng

**Comment by GeoGroup** [comment]
Thanks for your reply.
